apiVersion: v1
kind: Service
metadata:
  name: toolbox-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: toolboxport
  selector:
    app: toolbox-app

