apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode
  labels:
    app: hadoop-datanode
spec:
  selector:
    matchLabels:
      app: hadoop-datanode
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - image: yiqiu2012/hadoop-datanode
          imagePullPolicy: Always
          name: hadoop-datanode
          ports:
            - containerPort: 5000
