apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-app
  labels:
    app: jupyter-app
spec:
  selector:
     matchLabels:
       app: jupyter-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: jupyter-app
    spec:
      containers:
        - image: jupyter/all-spark-notebook 
          imagePullPolicy: Always
          name: jupyter-app
          ports:
            - containerPort: 8888