apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: my-release-spark-master-svc