apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
      name: sonarservice
  selector:
    app: sonarqube-app
